// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4b6hKcCW5DFW2lKrAv39fioMfoyFKtyI',
    appId: '1:889507384517:web:f7b9d874b9932a1a99b4ac',
    messagingSenderId: '889507384517',
    projectId: 'ecominds2-3c623',
    authDomain: 'ecominds2-3c623.firebaseapp.com',
    storageBucket: 'ecominds2-3c623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2Sagly5KN1LImoeeCl6PvFgtpJm7w4s',
    appId: '1:889507384517:android:3e172a6daa0bdc2c99b4ac',
    messagingSenderId: '889507384517',
    projectId: 'ecominds2-3c623',
    storageBucket: 'ecominds2-3c623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvqZfHp2YYkwbmgGigHQkgFY6z0dTVAO0',
    appId: '1:889507384517:ios:c016fe42b8472bb299b4ac',
    messagingSenderId: '889507384517',
    projectId: 'ecominds2-3c623',
    storageBucket: 'ecominds2-3c623.firebasestorage.app',
    iosBundleId: 'com.example.masterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvqZfHp2YYkwbmgGigHQkgFY6z0dTVAO0',
    appId: '1:889507384517:ios:c016fe42b8472bb299b4ac',
    messagingSenderId: '889507384517',
    projectId: 'ecominds2-3c623',
    storageBucket: 'ecominds2-3c623.firebasestorage.app',
    iosBundleId: 'com.example.masterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4b6hKcCW5DFW2lKrAv39fioMfoyFKtyI',
    appId: '1:889507384517:web:e8efffaae8f22cd899b4ac',
    messagingSenderId: '889507384517',
    projectId: 'ecominds2-3c623',
    authDomain: 'ecominds2-3c623.firebaseapp.com',
    storageBucket: 'ecominds2-3c623.firebasestorage.app',
  );
}
